//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaReader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaReader.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Input_Add {
            get {
                return ResourceManager.GetString("Input_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ссылку на мангу.
        /// </summary>
        public static string Input_Text {
            get {
                return ResourceManager.GetString("Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввод.
        /// </summary>
        public static string Input_Title {
            get {
                return ResourceManager.GetString("Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Library_Action_Add {
            get {
                return ResourceManager.GetString("Library_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Library_Action_Settings {
            get {
                return ResourceManager.GetString("Library_Action_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка c мангой не найдена.
        /// </summary>
        public static string Library_Status_FolderNotFound {
            get {
                return ResourceManager.GetString("Library_Status_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлена манга .
        /// </summary>
        public static string Library_Status_MangaAdded {
            get {
                return ResourceManager.GetString("Library_Status_MangaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалена манга .
        /// </summary>
        public static string Library_Status_MangaRemoved {
            get {
                return ResourceManager.GetString("Library_Status_MangaRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление .
        /// </summary>
        public static string Library_Status_MangaUpdate {
            get {
                return ResourceManager.GetString("Library_Status_MangaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление манги.
        /// </summary>
        public static string Library_Status_Update {
            get {
                return ResourceManager.GetString("Library_Status_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление манги завершено.
        /// </summary>
        public static string Library_Status_UpdateComplete {
            get {
                return ResourceManager.GetString("Library_Status_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку.
        /// </summary>
        public static string Manga_Action_OpenFolder {
            get {
                return ResourceManager.GetString("Manga_Action_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Manga_Action_Remove {
            get {
                return ResourceManager.GetString("Manga_Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите удалить {0} ?.
        /// </summary>
        public static string Manga_Action_Remove_Confirm {
            get {
                return ResourceManager.GetString("Manga_Action_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Manga_Action_Update {
            get {
                return ResourceManager.GetString("Manga_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть сайт.
        /// </summary>
        public static string Manga_Action_View {
            get {
                return ResourceManager.GetString("Manga_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите действие.
        /// </summary>
        public static string Manga_Dialog_Content {
            get {
                return ResourceManager.GetString("Manga_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод: завершен.
        /// </summary>
        public static string Manga_IsCompleted {
            get {
                return ResourceManager.GetString("Manga_IsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернет недоступен.
        /// </summary>
        public static string Page_GetPage_InternetOff {
            get {
                return ResourceManager.GetString("Page_GetPage_InternetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Settings_ChangeButton {
            get {
                return ResourceManager.GetString("Settings_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сжимать мангу после скачивания.
        /// </summary>
        public static string Settings_Compress {
            get {
                return ResourceManager.GetString("Settings_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивать мангу в:.
        /// </summary>
        public static string Settings_DownloadMangaTo {
            get {
                return ResourceManager.GetString("Settings_DownloadMangaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык по умолчанию:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык влияет на названия манги в архивах и в библиотеке..
        /// </summary>
        public static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять мангу вместо полного скачивания.
        /// </summary>
        public static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять программу при запуске.
        /// </summary>
        public static string Settings_UpdateReader {
            get {
                return ResourceManager.GetString("Settings_UpdateReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MangaReader.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия: {0}.{1}.{2}.
        /// </summary>
        public static string Update_Label_Version {
            get {
                return ResourceManager.GetString("Update_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История версий.
        /// </summary>
        public static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
