//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaReader.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaReader.Avalonia.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запущено автоматическое обновление..
        /// </summary>
        internal static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Input_Login {
            get {
                return ResourceManager.GetString("Input_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Input_Logout {
            get {
                return ResourceManager.GetString("Input_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполните вход и выберите мангу из закладок или введите ссылку на мангу.
        /// </summary>
        internal static string Input_Text {
            get {
                return ResourceManager.GetString("Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление манги.
        /// </summary>
        internal static string Input_Title {
            get {
                return ResourceManager.GetString("Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Library_Action_Add {
            get {
                return ResourceManager.GetString("Library_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Library_Action_Settings {
            get {
                return ResourceManager.GetString("Library_Action_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить обновления.
        /// </summary>
        internal static string Library_CheckUpdate {
            get {
                return ResourceManager.GetString("Library_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Library_Exit {
            get {
                return ResourceManager.GetString("Library_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка c мангой не найдена.
        /// </summary>
        internal static string Library_Status_FolderNotFound {
            get {
                return ResourceManager.GetString("Library_Status_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлена манга .
        /// </summary>
        internal static string Library_Status_MangaAdded {
            get {
                return ResourceManager.GetString("Library_Status_MangaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалена манга .
        /// </summary>
        internal static string Library_Status_MangaRemoved {
            get {
                return ResourceManager.GetString("Library_Status_MangaRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление .
        /// </summary>
        internal static string Library_Status_MangaUpdate {
            get {
                return ResourceManager.GetString("Library_Status_MangaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление манги.
        /// </summary>
        internal static string Library_Status_Update {
            get {
                return ResourceManager.GetString("Library_Status_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление манги завершено.
        /// </summary>
        internal static string Library_Status_UpdateComplete {
            get {
                return ResourceManager.GetString("Library_Status_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string Library_TypeFilter_All {
            get {
                return ResourceManager.GetString("Library_TypeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить архивацию.
        /// </summary>
        internal static string Manga_Action_Compress {
            get {
                return ResourceManager.GetString("Manga_Action_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть папку.
        /// </summary>
        internal static string Manga_Action_OpenFolder {
            get {
                return ResourceManager.GetString("Manga_Action_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пауза.
        /// </summary>
        internal static string Manga_Action_Pause {
            get {
                return ResourceManager.GetString("Manga_Action_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Manga_Action_Remove {
            get {
                return ResourceManager.GetString("Manga_Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить {0} ?.
        /// </summary>
        internal static string Manga_Action_Remove_Confirm {
            get {
                return ResourceManager.GetString("Manga_Action_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Manga_Action_Restore {
            get {
                return ResourceManager.GetString("Manga_Action_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Manga_Action_Update {
            get {
                return ResourceManager.GetString("Manga_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть сайт.
        /// </summary>
        internal static string Manga_Action_View {
            get {
                return ResourceManager.GetString("Manga_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string Manga_Dialog_Content {
            get {
                return ResourceManager.GetString("Manga_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string Manga_Downloaded {
            get {
                return ResourceManager.GetString("Manga_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод: (.*).
        /// </summary>
        internal static string Manga_IsCompleted {
            get {
                return ResourceManager.GetString("Manga_IsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Manga_Name {
            get {
                return ResourceManager.GetString("Manga_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обновлять.
        /// </summary>
        internal static string Manga_NotUpdate {
            get {
                return ResourceManager.GetString("Manga_NotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        internal static string Manga_Settings {
            get {
                return ResourceManager.GetString("Manga_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод.
        /// </summary>
        internal static string Manga_Translate {
            get {
                return ResourceManager.GetString("Manga_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять.
        /// </summary>
        internal static string Manga_Update {
            get {
                return ResourceManager.GetString("Manga_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивация завершена..
        /// </summary>
        internal static string Mangas_Compress_Completed {
            get {
                return ResourceManager.GetString("Mangas_Compress_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивация .
        /// </summary>
        internal static string Mangas_Compress_Started {
            get {
                return ResourceManager.GetString("Mangas_Compress_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет недоступен.
        /// </summary>
        internal static string Page_GetPage_InternetOff {
            get {
                return ResourceManager.GetString("Page_GetPage_InternetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string Settings_ChangeButton {
            get {
                return ResourceManager.GetString("Settings_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архивировать мангу после скачивания.
        /// </summary>
        internal static string Settings_Compress {
            get {
                return ResourceManager.GetString("Settings_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачивать мангу в:.
        /// </summary>
        internal static string Settings_DownloadMangaTo {
            get {
                return ResourceManager.GetString("Settings_DownloadMangaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ именования папок.
        /// </summary>
        internal static string Settings_FolderNaming {
            get {
                return ResourceManager.GetString("Settings_FolderNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to часов.
        /// </summary>
        internal static string Settings_Hours {
            get {
                return ResourceManager.GetString("Settings_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык по умолчанию:.
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык влияет на названия манги в архивах и в библиотеке..
        /// </summary>
        internal static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сворачивать в трей.
        /// </summary>
        internal static string Settings_MinimizeToTray {
            get {
                return ResourceManager.GetString("Settings_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скин (изменяется после перезапуска).
        /// </summary>
        internal static string Settings_Skin {
            get {
                return ResourceManager.GetString("Settings_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        internal static string Settings_Sort {
            get {
                return ResourceManager.GetString("Settings_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать свёрнутой в трей.
        /// </summary>
        internal static string Settings_StartAppMinimizedToTray {
            get {
                return ResourceManager.GetString("Settings_StartAppMinimizedToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять мангу вместо полного скачивания.
        /// </summary>
        internal static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять мангу через каждые.
        /// </summary>
        internal static string Settings_UpdateEver {
            get {
                return ResourceManager.GetString("Settings_UpdateEver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять программу при запуске.
        /// </summary>
        internal static string Settings_UpdateReader {
            get {
                return ResourceManager.GetString("Settings_UpdateReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MangaReader.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия: {0}.
        /// </summary>
        internal static string Update_Label_Version {
            get {
                return ResourceManager.GetString("Update_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История версий.
        /// </summary>
        internal static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
