//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaReader.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaReader.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запущено автоматическое обновление..
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Input_Login {
            get {
                return ResourceManager.GetString("Input_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Input_Logout {
            get {
                return ResourceManager.GetString("Input_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход и выберите мангу из закладок или введите ссылку на мангу.
        /// </summary>
        public static string Input_Text {
            get {
                return ResourceManager.GetString("Input_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление манги.
        /// </summary>
        public static string Input_Title {
            get {
                return ResourceManager.GetString("Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Library_Action_Add {
            get {
                return ResourceManager.GetString("Library_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Library_Action_Settings {
            get {
                return ResourceManager.GetString("Library_Action_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить обновления.
        /// </summary>
        public static string Library_CheckUpdate {
            get {
                return ResourceManager.GetString("Library_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Library_Exit {
            get {
                return ResourceManager.GetString("Library_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка c мангой не найдена.
        /// </summary>
        public static string Library_Status_FolderNotFound {
            get {
                return ResourceManager.GetString("Library_Status_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлена манга .
        /// </summary>
        public static string Library_Status_MangaAdded {
            get {
                return ResourceManager.GetString("Library_Status_MangaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалена манга .
        /// </summary>
        public static string Library_Status_MangaRemoved {
            get {
                return ResourceManager.GetString("Library_Status_MangaRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление .
        /// </summary>
        public static string Library_Status_MangaUpdate {
            get {
                return ResourceManager.GetString("Library_Status_MangaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление манги.
        /// </summary>
        public static string Library_Status_Update {
            get {
                return ResourceManager.GetString("Library_Status_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление манги завершено.
        /// </summary>
        public static string Library_Status_UpdateComplete {
            get {
                return ResourceManager.GetString("Library_Status_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string Library_TypeFilter_All {
            get {
                return ResourceManager.GetString("Library_TypeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация не была пройдена. Неверный логин или пароль?.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить архивацию.
        /// </summary>
        public static string Manga_Action_Compress {
            get {
                return ResourceManager.GetString("Manga_Action_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку.
        /// </summary>
        public static string Manga_Action_OpenFolder {
            get {
                return ResourceManager.GetString("Manga_Action_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза.
        /// </summary>
        public static string Manga_Action_Pause {
            get {
                return ResourceManager.GetString("Manga_Action_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Manga_Action_Remove {
            get {
                return ResourceManager.GetString("Manga_Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите удалить {0} ?.
        /// </summary>
        public static string Manga_Action_Remove_Confirm {
            get {
                return ResourceManager.GetString("Manga_Action_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string Manga_Action_Restore {
            get {
                return ResourceManager.GetString("Manga_Action_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Manga_Action_Update {
            get {
                return ResourceManager.GetString("Manga_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть сайт.
        /// </summary>
        public static string Manga_Action_View {
            get {
                return ResourceManager.GetString("Manga_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите действие.
        /// </summary>
        public static string Manga_Dialog_Content {
            get {
                return ResourceManager.GetString("Manga_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружено.
        /// </summary>
        public static string Manga_Downloaded {
            get {
                return ResourceManager.GetString("Manga_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод: (.*).
        /// </summary>
        public static string Manga_IsCompleted {
            get {
                return ResourceManager.GetString("Manga_IsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string Manga_Name {
            get {
                return ResourceManager.GetString("Manga_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не обновлять.
        /// </summary>
        public static string Manga_NotUpdate {
            get {
                return ResourceManager.GetString("Manga_NotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойства.
        /// </summary>
        public static string Manga_Settings {
            get {
                return ResourceManager.GetString("Manga_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод.
        /// </summary>
        public static string Manga_Translate {
            get {
                return ResourceManager.GetString("Manga_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять.
        /// </summary>
        public static string Manga_Update {
            get {
                return ResourceManager.GetString("Manga_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архивация завершена..
        /// </summary>
        public static string Mangas_Compress_Completed {
            get {
                return ResourceManager.GetString("Mangas_Compress_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архивация .
        /// </summary>
        public static string Mangas_Compress_Started {
            get {
                return ResourceManager.GetString("Mangas_Compress_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт недоступен.
        /// </summary>
        public static string Page_GetPage_SiteOff {
            get {
                return ResourceManager.GetString("Page_GetPage_SiteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Settings_ChangeButton {
            get {
                return ResourceManager.GetString("Settings_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архивировать мангу после скачивания.
        /// </summary>
        public static string Settings_Compress {
            get {
                return ResourceManager.GetString("Settings_Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивать мангу в:.
        /// </summary>
        public static string Settings_DownloadMangaTo {
            get {
                return ResourceManager.GetString("Settings_DownloadMangaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на часов.
        /// </summary>
        public static string Settings_Hours {
            get {
                return ResourceManager.GetString("Settings_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык по умолчанию:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык влияет на названия манги в архивах и в библиотеке..
        /// </summary>
        public static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сворачивать в трей.
        /// </summary>
        public static string Settings_MinimizeToTray {
            get {
                return ResourceManager.GetString("Settings_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять мангу вместо полного скачивания.
        /// </summary>
        public static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять мангу через каждые.
        /// </summary>
        public static string Settings_UpdateEver {
            get {
                return ResourceManager.GetString("Settings_UpdateEver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлять программу при запуске.
        /// </summary>
        public static string Settings_UpdateReader {
            get {
                return ResourceManager.GetString("Settings_UpdateReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MangaReader.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия: {0}.
        /// </summary>
        public static string Update_Label_Version {
            get {
                return ResourceManager.GetString("Update_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История версий.
        /// </summary>
        public static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
    }
}
